apiVersion: v1
kind: Service
metadata:
  name: observer-api
  namespace: {{ .Values.namespace }}
  labels:
    app: 5g-observer-api
    app.kubernetes.io/name: 5g-observer
spec:
  selector:
    app: 5g-observer-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 9999
      targetPort: 9999
      protocol: TCP
  type: ClusterIP
