apiVersion: v1
kind: Service
metadata:
  name: 5g-observer-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: 5g-observer-frontend
    app.kubernetes.io/name: 5g-observer
spec:
  selector:
    app: 5g-observer-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
